version: '3'

services:
  sleek-airflow:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.airflow 
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
    entrypoint: ["/bin/sh", "-c"]
    command: ["rm -f /opt/airflow/airflow-webserver.pid && exec airflow standalone"]
    networks:
      - app-network

  flask-api:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.flask 
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
